### ISSUE TITLE
Return to DemoRRateRequestor

### ISSUE THREAD

**Issue by ddunsmuir** [part-cw/LNhealth#8]
@ionathanch When I launch RRate from DemoRRateRequestor on iOS and then finish a measurement and press Yes to the confirmation question, the value goes back to DemoRRateRequestor, but it does not open and RRate does not close. You need to switch back manually. Did you not get this piece to work on iOS? I see this behaviour in iOS 9.3.5 and iOS 12.1.

**Comment by ionathanch** [comment]
Did you add the [requester stuff](https://github.com/part-cw/LNhealth/wiki/Index-of-Module-sharevitalsigns-for-ios#requester) to DemoRRateRequestor?

**Comment by ddunsmuir** [comment]
Of course not, that would make entirely too much sense. I guess I need to learn to follow directions. Thanks, it's working now.

**Comment by ddunsmuir** [comment]
Fixed with commit [4a10453](https://github.com/part-cw/LNhealth/commit/4a104531a1bfd2f235ed1afa599953abf2f87d13)
